const Register = () => {
  return (
    <>
      <div className='classes here'>
        <h1>Register</h1>
        <form>
          <fieldset>
            <legend>Personal Details</legend>
            <label for="fname">First Name:</label>
            <input type="text" id="fname" name="first_name" required>
            <br>
            <label for="lname">Last Name:</label>
            <input type="text" id="lname" name="last_name">
            <br>
            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required>
          </fieldset>
          <fieldset>
            <legend>Account Details</legend>
            <label for="username">Create a username:</label>
            <input type="text" id="username" name="username" required>
            <br>
            <label for="password1">Create a password:</label>
            <input type="password" id="password1" name="password1" required>
            <br>
            <label for="password2">Confirm your password:</label>
            <input type="password" id="password2" name="password2" required>
          </fieldset>
          <fieldset>
            <legend>Your Location</legend>
            <label for="time_zone">Your time zone:</label>
            <select id="time_zone" name="time_zone" required>
              <option value="Hawaii">(GMT-10:00) Hawaii</option>
              <option value="Alaska">(GMT-09:00) Alaska</option>
              <option value="Pacific Time (US &amp; Canada)">(GMT-08:00) Pacific Time (US &amp; Canada)</option>
              <option value="Arizona">(GMT-07:00) Arizona</option>
              <option value="Mountain Time (US &amp; Canada)">(GMT-07:00) Mountain Time (US &amp; Canada)</option>
              <option value="Central Time (US &amp; Canada)" selected="selected">(GMT-06:00) Central Time (US &amp; Canada)</option>
              <option value="Eastern Time (US &amp; Canada)">(GMT-05:00) Eastern Time (US &amp; Canada)</option>
              <option value="Indiana (East)">(GMT-05:00) Indiana (East)</option><option value="" disabled="disabled">-------------</option>
              <option value="International Date Line West">(GMT-11:00) International Date Line West</option>
              <option value="Midway Island">(GMT-11:00) Midway Island</option>
              <option value="Samoa">(GMT-11:00) Samoa</option>
              <option value="Tijuana">(GMT-08:00) Tijuana</option>
              <option value="Chihuahua">(GMT-07:00) Chihuahua</option>
              <option value="Mazatlan">(GMT-07:00) Mazatlan</option>
              <option value="Central America">(GMT-06:00) Central America</option>
              <option value="Guadalajara">(GMT-06:00) Guadalajara</option>
              <option value="Mexico City">(GMT-06:00) Mexico City</option>
              <option value="Monterrey">(GMT-06:00) Monterrey</option>
              <option value="Saskatchewan">(GMT-06:00) Saskatchewan</option>
              <option value="Bogota">(GMT-05:00) Bogota</option>
              <option value="Lima">(GMT-05:00) Lima</option>
              <option value="Quito">(GMT-05:00) Quito</option>
              <option value="Caracas">(GMT-04:30) Caracas</option>
              <option value="Atlantic Time (Canada)">(GMT-04:00) Atlantic Time (Canada)</option>
              <option value="La Paz">(GMT-04:00) La Paz</option>
              <option value="Santiago">(GMT-04:00) Santiago</option>
              <option value="Newfoundland">(GMT-03:30) Newfoundland</option>
              <option value="Brasilia">(GMT-03:00) Brasilia</option>
              <option value="Buenos Aires">(GMT-03:00) Buenos Aires</option>
              <option value="Georgetown">(GMT-03:00) Georgetown</option>
              <option value="Greenland">(GMT-03:00) Greenland</option>
              <option value="Mid-Atlantic">(GMT-02:00) Mid-Atlantic</option>
              <option value="Azores">(GMT-01:00) Azores</option>
              <option value="Cape Verde Is.">(GMT-01:00) Cape Verde Is.</option>
              <option value="Casablanca">(GMT) Casablanca</option>
              <option value="Dublin">(GMT) Dublin</option>
              <option value="Edinburgh">(GMT) Edinburgh</option>
              <option value="Lisbon">(GMT) Lisbon</option>
              <option value="London">(GMT) London</option>
              <option value="Monrovia">(GMT) Monrovia</option>
              <option value="Amsterdam">(GMT+01:00) Amsterdam</option>
              <option value="Belgrade">(GMT+01:00) Belgrade</option>
              <option value="Berlin">(GMT+01:00) Berlin</option>
              <option value="Bern">(GMT+01:00) Bern</option>
              <option value="Bratislava">(GMT+01:00) Bratislava</option>
              <option value="Brussels">(GMT+01:00) Brussels</option>
              <option value="Budapest">(GMT+01:00) Budapest</option>
              <option value="Copenhagen">(GMT+01:00) Copenhagen</option>
              <option value="Ljubljana">(GMT+01:00) Ljubljana</option>
              <option value="Madrid">(GMT+01:00) Madrid</option>
              <option value="Paris">(GMT+01:00) Paris</option>
              <option value="Prague">(GMT+01:00) Prague</option>
              <option value="Rome">(GMT+01:00) Rome</option>
              <option value="Sarajevo">(GMT+01:00) Sarajevo</option>
              <option value="Skopje">(GMT+01:00) Skopje</option>
              <option value="Stockholm">(GMT+01:00) Stockholm</option>
              <option value="Vienna">(GMT+01:00) Vienna</option>
              <option value="Warsaw">(GMT+01:00) Warsaw</option>
              <option value="West Central Africa">(GMT+01:00) West Central Africa</option>
              <option value="Zagreb">(GMT+01:00) Zagreb</option>
              <option value="Athens">(GMT+02:00) Athens</option>
              <option value="Bucharest">(GMT+02:00) Bucharest</option>
              <option value="Cairo">(GMT+02:00) Cairo</option>
              <option value="Harare">(GMT+02:00) Harare</option>
              <option value="Helsinki">(GMT+02:00) Helsinki</option>
              <option value="Istanbul">(GMT+02:00) Istanbul</option>
              <option value="Jerusalem">(GMT+02:00) Jerusalem</option>
              <option value="Kyiv">(GMT+02:00) Kyiv</option>
              <option value="Minsk">(GMT+02:00) Minsk</option>
              <option value="Pretoria">(GMT+02:00) Pretoria</option>
              <option value="Riga">(GMT+02:00) Riga</option>
              <option value="Sofia">(GMT+02:00) Sofia</option>
              <option value="Tallinn">(GMT+02:00) Tallinn</option>
              <option value="Vilnius">(GMT+02:00) Vilnius</option>
              <option value="Baghdad">(GMT+03:00) Baghdad</option>
              <option value="Kuwait">(GMT+03:00) Kuwait</option>
              <option value="Moscow">(GMT+03:00) Moscow</option>
              <option value="Nairobi">(GMT+03:00) Nairobi</option>
              <option value="Riyadh">(GMT+03:00) Riyadh</option>
              <option value="St. Petersburg">(GMT+03:00) St. Petersburg</option>
              <option value="Volgograd">(GMT+03:00) Volgograd</option>
              <option value="Tehran">(GMT+03:30) Tehran</option>
              <option value="Abu Dhabi">(GMT+04:00) Abu Dhabi</option>
              <option value="Baku">(GMT+04:00) Baku</option>
              <option value="Muscat">(GMT+04:00) Muscat</option>
              <option value="Tbilisi">(GMT+04:00) Tbilisi</option>
              <option value="Yerevan">(GMT+04:00) Yerevan</option>
              <option value="Kabul">(GMT+04:30) Kabul</option>
              <option value="Ekaterinburg">(GMT+05:00) Ekaterinburg</option>
              <option value="Islamabad">(GMT+05:00) Islamabad</option>
              <option value="Karachi">(GMT+05:00) Karachi</option>
              <option value="Tashkent">(GMT+05:00) Tashkent</option>
              <option value="Chennai">(GMT+05:30) Chennai</option>
              <option value="Kolkata">(GMT+05:30) Kolkata</option>
              <option value="Mumbai">(GMT+05:30) Mumbai</option>
              <option value="New Delhi">(GMT+05:30) New Delhi</option>
              <option value="Kathmandu">(GMT+05:45) Kathmandu</option>
              <option value="Almaty">(GMT+06:00) Almaty</option>
              <option value="Astana">(GMT+06:00) Astana</option>
              <option value="Dhaka">(GMT+06:00) Dhaka</option>
              <option value="Novosibirsk">(GMT+06:00) Novosibirsk</option>
              <option value="Sri Jayawardenepura">(GMT+06:00) Sri Jayawardenepura</option>
              <option value="Rangoon">(GMT+06:30) Rangoon</option>
              <option value="Bangkok">(GMT+07:00) Bangkok</option>
              <option value="Hanoi">(GMT+07:00) Hanoi</option>
              <option value="Jakarta">(GMT+07:00) Jakarta</option>
              <option value="Krasnoyarsk">(GMT+07:00) Krasnoyarsk</option>
              <option value="Beijing">(GMT+08:00) Beijing</option>
              <option value="Chongqing">(GMT+08:00) Chongqing</option>
              <option value="Hong Kong">(GMT+08:00) Hong Kong</option>
              <option value="Irkutsk">(GMT+08:00) Irkutsk</option>
              <option value="Kuala Lumpur">(GMT+08:00) Kuala Lumpur</option>
              <option value="Perth">(GMT+08:00) Perth</option>
              <option value="Singapore">(GMT+08:00) Singapore</option>
              <option value="Taipei">(GMT+08:00) Taipei</option>
              <option value="Ulaan Bataar">(GMT+08:00) Ulaan Bataar</option>
              <option value="Urumqi">(GMT+08:00) Urumqi</option>
              <option value="Osaka">(GMT+09:00) Osaka</option>
              <option value="Sapporo">(GMT+09:00) Sapporo</option>
              <option value="Seoul">(GMT+09:00) Seoul</option>
              <option value="Tokyo">(GMT+09:00) Tokyo</option>
              <option value="Yakutsk">(GMT+09:00) Yakutsk</option>
              <option value="Adelaide">(GMT+09:30) Adelaide</option>
              <option value="Darwin">(GMT+09:30) Darwin</option>
              <option value="Brisbane">(GMT+10:00) Brisbane</option>
              <option value="Canberra">(GMT+10:00) Canberra</option>
              <option value="Guam">(GMT+10:00) Guam</option>
              <option value="Hobart">(GMT+10:00) Hobart</option>
              <option value="Melbourne">(GMT+10:00) Melbourne</option>
              <option value="Port Moresby">(GMT+10:00) Port Moresby</option>
              <option value="Sydney">(GMT+10:00) Sydney</option>
              <option value="Vladivostok">(GMT+10:00) Vladivostok</option>
              <option value="Magadan">(GMT+11:00) Magadan</option>
              <option value="New Caledonia">(GMT+11:00) New Caledonia</option>
              <option value="Solomon Is.">(GMT+11:00) Solomon Is.</option>
              <option value="Auckland">(GMT+12:00) Auckland</option>
              <option value="Fiji">(GMT+12:00) Fiji</option>
              <option value="Kamchatka">(GMT+12:00) Kamchatka</option>
              <option value="Marshall Is.">(GMT+12:00) Marshall Is.</option>
              <option value="Wellington">(GMT+12:00) Wellington</option>
              <option value="Nuku'alofa">(GMT+13:00) Nuku'alofa</option>
	          </select>
            <br>
            <label for="country">Your country of residence:</label>
            <select id="country" name="country" required>
              <option>country</option>
              <option value="AF">Afghanistan</option>
              <option value="AX">Åland Islands</option>
              <option value="AL">Albania</option>
              <option value="DZ">Algeria</option>
              <option value="AS">American Samoa</option>
              <option value="AD">Andorra</option>
              <option value="AO">Angola</option>
              <option value="AI">Anguilla</option>
              <option value="AQ">Antarctica</option>
              <option value="AG">Antigua & Barbuda</option>
              <option value="AR">Argentina</option>
              <option value="AM">Armenia</option>
              <option value="AW">Aruba</option>
              <option value="AU">Australia</option>
              <option value="AT">Austria</option>
              <option value="AZ">Azerbaijan</option>
              <option value="BS">Bahamas</option>
              <option value="BH">Bahrain</option>
              <option value="BD">Bangladesh</option>
              <option value="BB">Barbados</option>
              <option value="BY">Belarus</option>
              <option value="BE">Belgium</option>
              <option value="BZ">Belize</option>
              <option value="BJ">Benin</option>
              <option value="BM">Bermuda</option>
              <option value="BT">Bhutan</option>
              <option value="BO">Bolivia</option>
              <option value="BQ">Caribbean Netherlands</option>
              <option value="BA">Bosnia & Herzegovina</option>
              <option value="BW">Botswana</option>
              <option value="BV">Bouvet Island</option>
              <option value="BR">Brazil</option>
              <option value="IO">British Indian Ocean Territory</option>
              <option value="BN">Brunei</option>
              <option value="BG">Bulgaria</option>
              <option value="BF">Burkina Faso</option>
              <option value="BI">Burundi</option>
              <option value="KH">Cambodia</option>
              <option value="CM">Cameroon</option>
              <option value="CA">Canada</option>
              <option value="CV">Cape Verde</option>
              <option value="KY">Cayman Islands</option>
              <option value="CF">Central African Republic</option>
              <option value="TD">Chad</option>
              <option value="CL">Chile</option>
              <option value="CN">China</option>
              <option value="CX">Christmas Island</option>
              <option value="CC">Cocos (Keeling) Islands</option>
              <option value="CO">Colombia</option>
              <option value="KM">Comoros</option>
              <option value="CG">Congo - Brazzaville</option>
              <option value="CD">Congo - Kinshasa</option>
              <option value="CK">Cook Islands</option>
              <option value="CR">Costa Rica</option>
              <option value="CI">Côte d'Ivoire</option>
              <option value="HR">Croatia</option>
              <option value="CU">Cuba</option>
              <option value="CW">Curaçao</option>
              <option value="CY">Cyprus</option>
              <option value="CZ">Czechia</option>
              <option value="DK">Denmark</option>
              <option value="DJ">Djibouti</option>
              <option value="DM">Dominica</option>
              <option value="DO">Dominican Republic</option>
              <option value="EC">Ecuador</option>
              <option value="EG">Egypt</option>
              <option value="SV">El Salvador</option>
              <option value="GQ">Equatorial Guinea</option>
              <option value="ER">Eritrea</option>
              <option value="EE">Estonia</option>
              <option value="ET">Ethiopia</option>
              <option value="FK">Falkland Islands (Islas Malvinas)</option>
              <option value="FO">Faroe Islands</option>
              <option value="FJ">Fiji</option>
              <option value="FI">Finland</option>
              <option value="FR">France</option>
              <option value="GF">French Guiana</option>
              <option value="PF">French Polynesia</option>
              <option value="TF">French Southern Territories</option>
              <option value="GA">Gabon</option>
              <option value="GM">Gambia</option>
              <option value="GE">Georgia</option>
              <option value="DE">Germany</option>
              <option value="GH">Ghana</option>
              <option value="GI">Gibraltar</option>
              <option value="GR">Greece</option>
              <option value="GL">Greenland</option>
              <option value="GD">Grenada</option>
              <option value="GP">Guadeloupe</option>
              <option value="GU">Guam</option>
              <option value="GT">Guatemala</option>
              <option value="GG">Guernsey</option>
              <option value="GN">Guinea</option>
              <option value="GW">Guinea-Bissau</option>
              <option value="GY">Guyana</option>
              <option value="HT">Haiti</option>
              <option value="HM">Heard & McDonald Islands</option>
              <option value="VA">Vatican City</option>
              <option value="HN">Honduras</option>
              <option value="HK">Hong Kong</option>
              <option value="HU">Hungary</option>
              <option value="IS">Iceland</option>
              <option value="IN">India</option>
              <option value="ID">Indonesia</option>
              <option value="IR">Iran</option>
              <option value="IQ">Iraq</option>
              <option value="IE">Ireland</option>
              <option value="IM">Isle of Man</option>
              <option value="IL">Israel</option>
              <option value="IT">Italy</option>
              <option value="JM">Jamaica</option>
              <option value="JP">Japan</option>
              <option value="JE">Jersey</option>
              <option value="JO">Jordan</option>
              <option value="KZ">Kazakhstan</option>
              <option value="KE">Kenya</option>
              <option value="KI">Kiribati</option>
              <option value="KP">North Korea</option>
              <option value="KR">South Korea</option>
              <option value="XK">Kosovo</option>
              <option value="KW">Kuwait</option>
              <option value="KG">Kyrgyzstan</option>
              <option value="LA">Laos</option>
              <option value="LV">Latvia</option>
              <option value="LB">Lebanon</option>
              <option value="LS">Lesotho</option>
              <option value="LR">Liberia</option>
              <option value="LY">Libya</option>
              <option value="LI">Liechtenstein</option>
              <option value="LT">Lithuania</option>
              <option value="LU">Luxembourg</option>
              <option value="MO">Macao</option>
              <option value="MK">North Macedonia</option>
              <option value="MG">Madagascar</option>
              <option value="MW">Malawi</option>
              <option value="MY">Malaysia</option>
              <option value="MV">Maldives</option>
              <option value="ML">Mali</option>
              <option value="MT">Malta</option>
              <option value="MH">Marshall Islands</option>
              <option value="MQ">Martinique</option>
              <option value="MR">Mauritania</option>
              <option value="MU">Mauritius</option>
              <option value="YT">Mayotte</option>
              <option value="MX">Mexico</option>
              <option value="FM">Micronesia</option>
              <option value="MD">Moldova</option>
              <option value="MC">Monaco</option>
              <option value="MN">Mongolia</option>
              <option value="ME">Montenegro</option>
              <option value="MS">Montserrat</option>
              <option value="MA">Morocco</option>
              <option value="MZ">Mozambique</option>
              <option value="MM">Myanmar (Burma)</option>
              <option value="NA">Namibia</option>
              <option value="NR">Nauru</option>
              <option value="NP">Nepal</option>
              <option value="NL">Netherlands</option>
              <option value="AN">Curaçao</option>
              <option value="NC">New Caledonia</option>
              <option value="NZ">New Zealand</option>
              <option value="NI">Nicaragua</option>
              <option value="NE">Niger</option>
              <option value="NG">Nigeria</option>
              <option value="NU">Niue</option>
              <option value="NF">Norfolk Island</option>
              <option value="MP">Northern Mariana Islands</option>
              <option value="NO">Norway</option>
              <option value="OM">Oman</option>
              <option value="PK">Pakistan</option>
              <option value="PW">Palau</option>
              <option value="PS">Palestine</option>
              <option value="PA">Panama</option>
              <option value="PG">Papua New Guinea</option>
              <option value="PY">Paraguay</option>
              <option value="PE">Peru</option>
              <option value="PH">Philippines</option>
              <option value="PN">Pitcairn Islands</option>
              <option value="PL">Poland</option>
              <option value="PT">Portugal</option>
              <option value="PR">Puerto Rico</option>
              <option value="QA">Qatar</option>
              <option value="RE">Réunion</option>
              <option value="RO">Romania</option>
              <option value="RU">Russia</option>
              <option value="RW">Rwanda</option>
              <option value="BL">St. Barthélemy</option>
              <option value="SH">St. Helena</option>
              <option value="KN">St. Kitts & Nevis</option>
              <option value="LC">St. Lucia</option>
              <option value="MF">St. Martin</option>
              <option value="PM">St. Pierre & Miquelon</option>
              <option value="VC">St. Vincent & Grenadines</option>
              <option value="WS">Samoa</option>
              <option value="SM">San Marino</option>
              <option value="ST">São Tomé & Príncipe</option>
              <option value="SA">Saudi Arabia</option>
              <option value="SN">Senegal</option>
              <option value="RS">Serbia</option>
              <option value="CS">Serbia</option>
              <option value="SC">Seychelles</option>
              <option value="SL">Sierra Leone</option>
              <option value="SG">Singapore</option>
              <option value="SX">Sint Maarten</option>
              <option value="SK">Slovakia</option>
              <option value="SI">Slovenia</option>
              <option value="SB">Solomon Islands</option>
              <option value="SO">Somalia</option>
              <option value="ZA">South Africa</option>
              <option value="GS">South Georgia & South Sandwich Islands</option>
              <option value="SS">South Sudan</option>
              <option value="ES">Spain</option>
              <option value="LK">Sri Lanka</option>
              <option value="SD">Sudan</option>
              <option value="SR">Suriname</option>
              <option value="SJ">Svalbard & Jan Mayen</option>
              <option value="SZ">Eswatini</option>
              <option value="SE">Sweden</option>
              <option value="CH">Switzerland</option>
              <option value="SY">Syria</option>
              <option value="TW">Taiwan</option>
              <option value="TJ">Tajikistan</option>
              <option value="TZ">Tanzania</option>
              <option value="TH">Thailand</option>
              <option value="TL">Timor-Leste</option>
              <option value="TG">Togo</option>
              <option value="TK">Tokelau</option>
              <option value="TO">Tonga</option>
              <option value="TT">Trinidad & Tobago</option>
              <option value="TN">Tunisia</option>
              <option value="TR">Turkey</option>
              <option value="TM">Turkmenistan</option>
              <option value="TC">Turks & Caicos Islands</option>
              <option value="TV">Tuvalu</option>
              <option value="UG">Uganda</option>
              <option value="UA">Ukraine</option>
              <option value="AE">United Arab Emirates</option>
              <option value="GB">United Kingdom</option>
              <option value="US">United States</option>
              <option value="UM">U.S. Outlying Islands</option>
              <option value="UY">Uruguay</option>
              <option value="UZ">Uzbekistan</option>
              <option value="VU">Vanuatu</option>
              <option value="VE">Venezuela</option>
              <option value="VN">Vietnam</option>
              <option value="VG">British Virgin Islands</option>
              <option value="VI">U.S. Virgin Islands</option>
              <option value="WF">Wallis & Futuna</option>
              <option value="EH">Western Sahara</option>
              <option value="YE">Yemen</option>
              <option value="ZM">Zambia</option>
              <option value="ZW">Zimbabwe</option>
            </select>
            <br>
            <label for="city">Your city of residence:</label>
            <input type="text" id="city" name="city">
          </fieldset>
          <button type="submit"></button>
        </form>
      </div>
    </>
  );
};

export default Register;
